### ISSUE TITLE
[Bug] Error popover is not showing when uploading labels

### ISSUE THREAD

**Issue by tthvo** [cryostatio/cryostat-web#997]
## Current Behavior:

After https://github.com/cryostatio/cryostat-web/pull/624, there is a popover that will show if any metadata files are invalid. However, it no longer shows.

## Expected Behavior:

Error popover should show if any metadata files are invalid.

## Steps To Reproduce:
1. With latest cryostat image, launch Cryostat.
2. Go to Archives and click Upload.
3. Expand metadata options and try uploading any invalid metadata files (a valid ones are usually downloaded with recordings and invalid ones can be any files with invalid JSON).
4. Notice how the popover does not show.
5. However, use browser inspector to check that the DOM node is mounted but popper css applies a hidden rule to the DOM.

## Anything else

There seems to be issues with mounting the upload modal on `portalRoot`. Somehow, the popper sees the button as clipped/hidden and apply `data-popper-reference-hidden` attribute to the popper div.

```css
/* Hide the popper when the reference is hidden */
#popper[data-popper-reference-hidden] {
  visibility: hidden;
  pointer-events: none;
}
```

See: https://popper.js.org/docs/v2/modifiers/hide/
